using System;
using System.Runtime.InteropServices;

namespace PisaciAutomat.Clipboard
{
    /// <summary>
    /// generated by Microsoft Bing Copilot...
    /// </summary>
    public class WindowsClipboardHelper
    {
        // Clipboard format constant for text
        private const uint CF_UNICODETEXT = 13;

        // P/Invoke declarations
        [DllImport("user32.dll", SetLastError = true)]
        private static extern bool OpenClipboard(IntPtr hWndNewOwner);

        [DllImport("user32.dll", SetLastError = true)]
        private static extern bool CloseClipboard();

        [DllImport("user32.dll", SetLastError = true)]
        private static extern IntPtr GetClipboardData(uint uFormat);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern IntPtr GlobalLock(IntPtr hMem);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern bool GlobalUnlock(IntPtr hMem);

        [DllImport("user32.dll", SetLastError = true)]
        private static extern bool EmptyClipboard();

        [DllImport("user32.dll", SetLastError = true)]
        private static extern IntPtr SetClipboardData(uint uFormat, IntPtr hMem);

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern IntPtr GlobalAlloc(uint uFlags, UIntPtr dwBytes);

        // Memory allocation flags
        private const uint GMEM_MOVEABLE = 0x0002;

        public static string GetClipboardText()
        {
            string result = null;

            try
            {
                if (!OpenClipboard(IntPtr.Zero))
                {
                    throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error(), "Unable to open clipboard.");
                }

                IntPtr handle = GetClipboardData(CF_UNICODETEXT);
                if (handle == IntPtr.Zero)
                {
                    throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error(), "No Unicode text data on clipboard.");
                }

                IntPtr pointer = GlobalLock(handle);
                if (pointer == IntPtr.Zero)
                {
                    throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error(), "Unable to lock global memory.");
                }

                try
                {
                    // Marshal the pointer to a .NET string
                    result = Marshal.PtrToStringUni(pointer);
                }
                finally
                {
                    GlobalUnlock(handle);
                }
            }
            finally
            {
                CloseClipboard();
            }

            return result;
        }

        public static bool SetClipboardText(string text)
        {
            if (string.IsNullOrEmpty(text))
                throw new ArgumentException("Text cannot be null or empty.", nameof(text));

            if (!OpenClipboard(IntPtr.Zero))
                throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error(), "Failed to open clipboard.");

            try
            {
                if (!EmptyClipboard())
                    throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error(), "Failed to empty clipboard.");

                // Allocate global memory for the text (including null terminator)
                var bytes = (text.Length + 1) * 2; // Unicode = 2 bytes per char
                IntPtr hGlobal = GlobalAlloc(GMEM_MOVEABLE, (UIntPtr)bytes);
                if (hGlobal == IntPtr.Zero)
                    throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error(), "GlobalAlloc failed.");

                // Lock memory and copy text
                IntPtr target = GlobalLock(hGlobal);
                if (target == IntPtr.Zero)
                    throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error(), "GlobalLock failed.");

                try
                {
                    // Copy string to unmanaged memory
                    Marshal.Copy(text.ToCharArray(), 0, target, text.Length);
                    Marshal.WriteInt16(target, text.Length * 2, 0); // Null terminator
                }
                finally
                {
                    GlobalUnlock(hGlobal);
                }

                // Pass ownership to the system
                if (SetClipboardData(CF_UNICODETEXT, hGlobal) == IntPtr.Zero)
                    throw new System.ComponentModel.Win32Exception(Marshal.GetLastWin32Error(), "SetClipboardData failed.");

                // Do NOT free hGlobal after SetClipboardData — system owns it now
                return true;
            }
            finally
            {
                CloseClipboard();
            }
        }
    }
}
