using System;
using System.Runtime.InteropServices;

namespace PSMat.Windows
{
    /// <summary>
    /// generated by Microsoft Bing Copilot
    /// 
    /// usage:
    //Thread hotkeyThread = new Thread(HotkeyListener.InterceptHotKeys)
    //{
    //    IsBackground = true // Ends when main app ends
    //};
    //hotkeyThread.Start();
    /// </summary>
    internal static class HotkeyListener
    {
        // Import WinAPI functions
        [DllImport("user32.dll")]
        private static extern bool RegisterHotKey(IntPtr hWnd, int id, uint fsModifiers, uint vk);

        [DllImport("user32.dll")]
        private static extern bool UnregisterHotKey(IntPtr hWnd, int id);

        [DllImport("user32.dll")]
        private static extern bool GetMessage(out MSG lpMsg, IntPtr hWnd, uint wMsgFilterMin, uint wMsgFilterMax);

        // Modifier keys
        private const uint MOD_ALT = 0x0001;
        private const uint MOD_CONTROL = 0x0002;
        private const uint MOD_SHIFT = 0x0004;
        private const uint MOD_WIN = 0x0008;

        // Windows message structure
        [StructLayout(LayoutKind.Sequential)]
        private struct MSG
        {
            public IntPtr hwnd;
            public uint message;
            public IntPtr wParam;
            public IntPtr lParam;
            public uint time;
            public POINT pt;
        }

        [StructLayout(LayoutKind.Sequential)]
        private struct POINT
        {
            public int x;
            public int y;
        }

        // Windows message constants
        private const int WM_HOTKEY = 0x0312;

        public static void InterceptHotKeys()
        {
            const int HOTKEY_ID = 1; // Unique ID for the hotkey

            //vk integer from https://learn.microsoft.com/de-de/dotnet/api/system.windows.forms.keys?view=windowsdesktop-10.0&redirectedfrom=MSDN
            if (!RegisterHotKey(IntPtr.Zero, HOTKEY_ID, MOD_CONTROL, (uint)86))
            {
                Console.WriteLine("Failed to register Ctrl+V hotkey. It may already be in use.");
                return;
            }

            try
            {
                // Message loop
                while (true)
                {
                    if (GetMessage(out MSG msg, IntPtr.Zero, 0, 0))
                    {
                        if (msg.message == WM_HOTKEY && msg.wParam.ToInt32() == HOTKEY_ID)
                        {
                            Console.WriteLine("Ctrl+V pressed at " + DateTime.Now);
                        }
                    }
                }
            }
            finally
            {
                // Always unregister on exit
                UnregisterHotKey(IntPtr.Zero, HOTKEY_ID);
            }
        }
    }
}
