using Newtonsoft.Json;
using PisaciAutomat.Obrazovka;
using PisaciStroj.Lexer;
using PisaciStroj.Testy;
using PSMat.Testy.Obrazovka;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace PSMat.Testy.Lexer
{
    public class LexerTest : ITest
    {
        public List<TestResult> Spust()
        {
            var r = new List<TestResult>();

            r.Add(new TestResult()
            {
                TestName = "SimpleCSharpFileSyntaxHighlight",
                Pass = BasicTest()
            });

            return r;
        }

        private bool BasicTest()
        {
            var gramatika = new LexGramatika()
            {
                JednoriadkovyKomentar = "//",
                ZaciatokKomentara = "/*",
                KoniecKomentara = "*/",
            };

            var lexer = new LexAutomat(gramatika);

            var text = SyntaxHighlightStubs.Riadky();
            var r = lexer.Lex(text);

            var parametreVykreslovania = SyntaxHighlightStubs.ParametreVypisu();
            parametreVykreslovania.Riadok = 1;

            var result = VykreslovaciAutomat.Precitaj2(
                parametreVykreslovania,
                SyntaxHighlightStubs.VysledkyVyhladavania(),
                r,
                new PisaciStroj.Program(text),
                new PisaciStroj.Parametre.ParametreVyberu(),
                new LexAutomat(new LexGramatika()));

            var sb = new StringBuilder();

            VykreslovaciAutomat.Vykresli(result, sb, new StavovyRiadokInfo(), parametreVykreslovania);

            var ansiKod = sb.ToString();

            var ocakavane = "\u001b[3;1H\u001b[2m000\u001b[0m  namespace ConsoleApp1\r\n\u001b[2m001\u001b[0m  \u001b[1;38;5;196m\u001b[48;5;250m{\u001b[0m\r\n\u001b[2m002\u001b[0m      /*\r\n\u001b[2m003\u001b[0m       * RegexAstTree is useful to construct deterministic finite automaton accepting language generated by regex\r\n\u001b[2m004\u001b[0m       */\r\n\u001b[2m005\u001b[0m      publicclass RegexAstTree\r\n\u001b[2m006\u001b[0m      \u001b[1;38;5;196m{\u001b[0m\r\n\u001b[2m007\u001b[0m  \r\n\u001b[2m008\u001b[0m          public Dictionary<int, HashSet<int>> FollowPos \u001b[1;38;5;196m{\u001b[0m get; private set; \u001b[1;38;5;196m}\u001b[0m\r\n\u001b[2m009\u001b[0m  //TODO make static?\r\n\u001b[2m010\u001b[0m          private static void BracketFun\u001b[1;38;5;196m(\u001b[0mint a, int b\u001b[1;38;5;196m)\u001b[0m\u001b[1;38;5;196m{\u001b[0m\r\n\u001b[2m011\u001b[0m              var x = \u001b[1;38;5;196m(\u001b[0m1 - \u001b[1;38;5;196m(\u001b[0m23 + 5\u001b[1;38;5;196m)\u001b[0m / 4 + \u001b[1;38;5;196m(\u001b[0m32 + a / " +
                            "\u001b[1;38;5;196m(\u001b[0mb - 1\u001b[1;38;5;196m)\u001b[0m\u001b[1;38;5;196m)\u001b[0m\u001b[1;38;5;196m)\u001b[0m)\r\n\u001b[2m012\u001b[0m          \u001b[1;38;5;196m}\u001b[0m\r\n\u001b[2m013\u001b[0m      \u001b[1;38;5;196m}\u001b[0m\r\n\u001b[2m014\u001b[0m  \u001b[1;38;5;196m\u001b[48;5;250m}\u001b[0m}}\r\n\r\n\u001b[20;6H\u001b[44;1m\u001b[0m\u001b[4;6H";


            var pass = ansiKod == ocakavane;

            return pass;
        }
    }
}
