<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PisaciAutomat\PisaciAutomat.csproj" />
    <ProjectReference Include="..\PisaciStroj\PisaciStroj.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Lexer\Config\CSharp.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
