name: PSMat unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-multiple:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        shell: pwsh
        run: ./scripts/Build-DotNet.ps1 -ProjectPath "./src/PSMat.sln" -Configuration Release
          
      - name: Test
        shell: pwsh
        run: ./scripts/Test-PSMat.ps1
